<?php

return [
    'meta' => [
        'tag' => 'Master Professional Catalogue',
        'title' => 'Every specialization, verified the same way.',
        'description' => 'One platform, 15 major service groups, 300+ professional specializations — every listing follows the same trusted verification framework before it ever reaches a customer.',
    ],

    'stats' => [
        ['value' => '15', 'label' => 'Major Service Groups'],
        ['value' => '300+', 'label' => 'Specializations'],
        ['value' => '16', 'label' => 'Verification Checks'],
        ['value' => '100%', 'label' => 'Profiles Verified'],
    ],

    'verification' => [
        'tag' => 'Our Verification Standard',
        'title' => 'Trust, checked sixteen ways.',
        'description' => 'Every professional listed on Taskora — from an electrician to a chartered accountant — clears the same verification framework before activation.',
        'checks' => [
            'CNIC Verification',
            'Mobile Verification',
            'Email Verification',
            'Address Verification',
            'Police Clearance (where applicable)',
            'Qualification Verification',
            'Experience Verification',
            'Trade License Verification',
            'SECP / NTN Verification',
            'Tax Compliance Verification',
            'Background Screening',
            'Customer Rating System',
            'Quality Inspection',
            'Insurance Eligibility',
            'Digital Service Record',
            'Continuous Performance Monitoring',
        ],
    ],

    'browse' => [
        'tag' => 'Browse By Category',
        'title' => 'The full catalogue.',
        'description' => 'Click a category to expand every specialization within it.',
    ],

    'categories' => [
        [
            'name' => 'Home Services',
            'count' => '10 groups · 74 specializations',
            'color' => 'green',
            'open' => true,
            'subcategories' => [
                [
                    'title' => 'Electrical Services',
                    'chips' => [
                        'Electricians',
                        'Wiring Specialists',
                        'Distribution Board Installation',
                        'Generator Installation',
                        'UPS Installation',
                        'Smart Home Electrical Systems',
                        'Lighting Installation',
                        'Emergency Electricians',
                    ],
                ],
                [
                    'title' => 'Plumbing Services',
                    'chips' => [
                        'Plumbers',
                        'Water Supply Specialists',
                        'Drainage Experts',
                        'Leak Detection',
                        'Sewerage Repair',
                        'Water Tank Installation',
                        'Bathroom Plumbing',
                        'Kitchen Plumbing',
                    ],
                ],
                [
                    'title' => 'HVAC & AC Services',
                    'chips' => [
                        'AC Installation',
                        'AC Repair',
                        'AC Maintenance',
                        'HVAC Engineers',
                        'Ventilation Systems',
                        'Chiller Specialists',
                        'Duct Cleaning',
                        'Refrigeration Technicians',
                    ],
                ],
                [
                    'title' => 'Home Cleaning',
                    'chips' => [
                        'Deep Cleaning',
                        'Sofa Cleaning',
                        'Carpet Cleaning',
                        'Kitchen Cleaning',
                        'Bathroom Cleaning',
                        'Glass Cleaning',
                        'Water Tank Cleaning',
                        'Post-Construction Cleaning',
                    ],
                ],
                [
                    'title' => 'Pest Control',
                    'chips' => [
                        'Termite Control',
                        'General Pest Control',
                        'Rodent Control',
                        'Mosquito Control',
                        'Fumigation Services',
                    ],
                ],
                [
                    'title' => 'Appliance Repair',
                    'chips' => [
                        'Refrigerator',
                        'Washing Machine',
                        'Microwave',
                        'Oven',
                        'Dishwasher',
                        'Water Dispenser',
                        'Small Appliances',
                    ],
                ],
                [
                    'title' => 'Carpentry',
                    'chips' => [
                        'Furniture Repair',
                        'Custom Furniture',
                        'Wardrobes',
                        'Kitchen Cabinets',
                        'Wooden Flooring',
                        'Door Installation',
                    ],
                ],
                [
                    'title' => 'Painting Services',
                    'chips' => [
                        'Interior Painting',
                        'Exterior Painting',
                        'Texture Paint',
                        'Decorative Paint',
                        'Waterproof Coating',
                    ],
                ],
                [
                    'title' => 'Gardening & Landscaping',
                    'chips' => [
                        'Garden Design',
                        'Lawn Maintenance',
                        'Tree Trimming',
                        'Irrigation',
                        'Plant Supply',
                    ],
                ],
                [
                    'title' => 'Moving & Shifting',
                    'chips' => [
                        'House Moving',
                        'Packing',
                        'Loading',
                        'Unloading',
                        'Storage Solutions',
                    ],
                ],
            ],
        ],
        [
            'name' => 'Construction & Property',
            'count' => '20 specializations',
            'color' => 'green-dark',
            'open' => false,
            'chips' => [
                'Civil Engineers',
                'Architects',
                'Interior Designers',
                'Structural Engineers',
                'Quantity Surveyors',
                'Project Managers',
                'Building Contractors',
                'Renovation Specialists',
                'Masonry Experts',
                'Tile Installation',
                'Marble & Granite',
                'Aluminum & Glass',
                'Steel Fabrication',
                'Roofing Contractors',
                'Waterproofing',
                'False Ceiling',
                'Flooring Specialists',
                'Property Inspectors',
                'Building Maintenance',
                'Smart Building Automation',
            ],
        ],
        [
            'name' => 'Property & Real Estate',
            'count' => '10 specializations',
            'color' => 'black',
            'open' => false,
            'chips' => [
                'Property Consultants',
                'Real Estate Agents',
                'Property Valuation Experts',
                'Property Documentation',
                'Property Verification',
                'Transfer Specialists',
                'Investment Advisors',
                'Facility Managers',
                'Rental Management',
                'Property Marketing',
            ],
        ],
        [
            'name' => 'Business Services',
            'count' => '10 specializations',
            'color' => 'gold',
            'open' => false,
            'chips' => [
                'Chartered Accountants',
                'Tax Consultants',
                'Auditors',
                'Bookkeepers',
                'Financial Consultants',
                'Payroll Specialists',
                'Company Registration',
                'Corporate Secretarial Services',
                'Business Licensing',
                'Compliance Consultants',
            ],
        ],
        [
            'name' => 'Legal Services',
            'count' => '11 specializations',
            'color' => 'green',
            'open' => false,
            'chips' => [
                'Lawyers',
                'Corporate Lawyers',
                'Property Lawyers',
                'Family Lawyers',
                'Civil Lawyers',
                'Criminal Lawyers',
                'Labour Lawyers',
                'Tax Lawyers',
                'Contract Drafting',
                'Legal Documentation',
                'Arbitration & Mediation',
            ],
        ],
        [
            'name' => 'HR & Recruitment',
            'count' => '8 specializations',
            'color' => 'green-dark',
            'open' => false,
            'chips' => [
                'HR Consultants',
                'Recruiters',
                'Payroll Management',
                'Background Verification',
                'Executive Search',
                'Corporate Training',
                'Performance Management',
                'HR Outsourcing',
            ],
        ],
        [
            'name' => 'IT & Technology',
            'count' => '15 specializations',
            'color' => 'black',
            'open' => false,
            'chips' => [
                'Software Developers',
                'Web Developers',
                'Mobile App Developers',
                'AI Engineers',
                'Data Scientists',
                'Cybersecurity Specialists',
                'Cloud Engineers',
                'DevOps Engineers',
                'ERP Consultants',
                'CRM Specialists',
                'UI/UX Designers',
                'QA Engineers',
                'Network Engineers',
                'IT Support',
                'Database Administrators',
            ],
        ],
        [
            'name' => 'Digital Marketing',
            'count' => '14 specializations',
            'color' => 'gold',
            'open' => false,
            'chips' => [
                'SEO Experts',
                'Social Media Managers',
                'PPC Specialists',
                'Google Ads',
                'Meta Ads',
                'Email Marketing',
                'Content Writers',
                'Copywriters',
                'Graphic Designers',
                'Brand Consultants',
                'Video Editors',
                'Motion Graphics',
                'Photography',
                'Videography',
            ],
        ],
        [
            'name' => 'Education',
            'count' => '9 specializations',
            'color' => 'green',
            'open' => false,
            'chips' => [
                'Tutors',
                'Language Teachers',
                'Science Teachers',
                'Mathematics Teachers',
                'Computer Instructors',
                'Quran Tutors',
                'Test Preparation',
                'Online Coaching',
                'Professional Trainers',
            ],
        ],
        [
            'name' => 'Health & Wellness',
            'count' => '8 specializations',
            'color' => 'green-dark',
            'open' => false,
            'chips' => [
                'Doctors (Partner Network)',
                'Physiotherapists',
                'Nutritionists',
                'Fitness Trainers',
                'Yoga Instructors',
                'Mental Wellness Coaches',
                'Home Nursing',
                'Elder Care',
            ],
        ],
        [
            'name' => 'Security Services',
            'count' => '7 specializations',
            'color' => 'black',
            'open' => false,
            'chips' => [
                'Security Guards',
                'CCTV Installation',
                'Access Control',
                'Alarm Systems',
                'Fire Safety',
                'Security Audits',
                'Event Security',
            ],
        ],
        [
            'name' => 'Logistics & Transport',
            'count' => '7 specializations',
            'color' => 'gold',
            'open' => false,
            'chips' => [
                'Courier Services',
                'Freight Forwarding',
                'Packers & Movers',
                'Warehousing',
                'Fleet Management',
                'Dispatch Services',
                'Last-Mile Delivery',
            ],
        ],
        [
            'name' => 'Event Services',
            'count' => '8 specializations',
            'color' => 'green',
            'open' => false,
            'chips' => [
                'Event Planners',
                'Wedding Planners',
                'Decorators',
                'Caterers',
                'Sound & Lighting',
                'Photography',
                'Videography',
                'Stage Management',
            ],
        ],
        [
            'name' => 'Corporate Services',
            'count' => '7 specializations',
            'color' => 'green-dark',
            'open' => false,
            'chips' => [
                'Office Administration',
                'Reception Services',
                'Document Management',
                'Office Maintenance',
                'Office Relocation',
                'Business Process Outsourcing',
                'Virtual Assistants',
            ],
        ],
        [
            'name' => 'Insurance & Financial Services',
            'count' => 'Partner-Based · 16 specializations',
            'color' => 'black',
            'open' => false,
            'chips' => [
                'Insurance Advisors',
                'Health Insurance',
                'Life Insurance',
                'Motor Insurance',
                'Property Insurance',
                'SME Insurance',
                'Takaful Services',
                'Savings Plans',
                'Budget Planning',
                'Gold Savings',
                'Retirement Planning',
                'Mutual Fund Referrals',
                'Investment Referrals',
                'SME Financing',
                'Invoice Financing',
                'Freelancer Banking Solutions',
            ],
            'note' => 'Taskora facilitates introductions to licensed banks, insurers, and brokerages — it does not hold customer funds or underwrite policies directly.',
        ],
    ],

    'profile' => [
        'tag' => 'Verified Professional Profile',
        'title' => 'What every listing shows you.',
        'description' => 'Every field below is captured, verified, and kept current before a customer ever books.',
        'name' => 'Imran Mahmood',
        'initials' => 'IM',
        'role' => 'HVAC & AC Services — Islamabad',
        'fields' => [
            ['label' => 'Professional ID', 'value' => 'TSK-AC-08421'],
            ['label' => 'Category', 'value' => 'HVAC & AC Services'],
            ['label' => 'Experience', 'value' => '9 Years'],
            ['label' => 'Qualifications', 'value' => 'HVAC Diploma, TEVTA'],
            ['label' => 'Languages', 'value' => 'Urdu, English'],
            ['label' => 'Service Areas', 'value' => 'Islamabad, Rawalpindi'],
            ['label' => 'Customer Rating', 'value' => '4.9 ★ (612 reviews)', 'tone' => 'gold'],
            ['label' => 'Completed Jobs', 'value' => '1,284'],
            ['label' => 'Response Time', 'value' => '< 12 min', 'tone' => 'green'],
            ['label' => 'Success Rate', 'value' => '98.4%', 'tone' => 'green'],
            ['label' => 'Warranty Offered', 'value' => '30 Days on Repairs'],
            ['label' => 'Emergency Availability', 'value' => 'Available', 'tone' => 'green'],
            ['label' => 'Insurance Status', 'value' => 'Covered'],
            ['label' => 'Pricing', 'value' => 'PKR 800 – 2,200 / visit'],
            ['label' => 'Digital Service History', 'value' => 'Available on request'],
        ],
    ],

    'quality' => [
        'tag' => 'Quality Promise',
        'title' => 'What every customer receives.',
        'items' => [
            'Verified Professional',
            'Transparent Pricing',
            'Digital Booking',
            'Live Job Tracking',
            'Secure Digital Payments',
            'Electronic Invoices',
            'Warranty (Where Applicable)',
            '24/7 Customer Support',
            'Complaint Resolution',
            'Digital Service History',
            'Verified Reviews',
            'Quality Assurance',
        ],
    ],

    'cta' => [
        'title' => 'Find the right professional, verified from day one.',
        'primary' => ['label' => 'Book a Service', 'href' => '/forms/booking'],
        'secondary' => ['label' => 'List Your Services', 'href' => '/register/provider'],
    ],
];
